version: '3.8'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:0.11.6
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=sqs,s3
    volumes:
      - ./init-scripts:/docker-entrypoint-initaws.d
